baseURL = 'https://www.julianagutierrezv.org/'
languageCode = 'es-CO'
title = 'Juliana Gutiérrez Valderrama'

defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = true
[languages]
  [languages.es]
    contentDir = 'content/es'
    languageCode = 'es-CO'
    languageName = 'Español'
    weight = 1
  [languages.en]
    contentDir = 'content/en'
    languageCode = 'en-US'
    languageName = 'English'
    weight = 2